name: Build
on:
  pull_request:
  push:
    branches:
      - main

env:
  GO_VERSION: "1.22"

jobs:
  codegen:
    name: Codegen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - run: go install github.com/google/wire/cmd/wire@latest
      - run: wire .
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'wire .' command and commit."; exit 1)
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test
        run: go test -cover -v ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64, mipsle]
        exclude:
          - os: darwin
            arch: mipsle
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: go build -v -o stunmesh-${{ matrix.os }}-${{ matrix.arch }} .
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
      - uses: actions/upload-artifact@v4
        with:
          name: stunmesh-${{ matrix.os }}-${{ matrix.arch }}
          path: stunmesh-${{ matrix.os }}-${{ matrix.arch }}
